name: sideboard_mtg
description: An all purpose MTG app built in Flutter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  envied: ^0.3.0+3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.4.4
  envied_generator: ^0.3.0+3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
