name: sideboard_mtg
description: An all purpose MTG app built in Flutter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.1.0
  bloc: ^8.1.1
  dart_openai: ^1.9.91
  dartz: ^0.10.1
  envied: ^0.3.0+3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^5.0.3
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  injectable_generator: ^2.1.5
  intl: ^0.18.0
  modular_bloc_bind: ^1.0.1

dev_dependencies:
  auto_route_generator: ^7.0.0
  bloc_test: ^9.1.1
  build_runner: ^2.4.4
  envied_generator: ^0.3.0+3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  injectable: ^2.1.1
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
