name: sideboard
description: An all purpose MTG app built in Flutter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.1.0
  bloc: ^8.1.1
  bloc_test: ^9.1.3
  dart_openai: ^2.0.1
  envied: ^0.3.0+3
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_bloc: ^8.1.2
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^5.0.3
  freezed_annotation: ^2.2.0
  gap: ^3.0.0
  get_it: ^7.6.0
  hydrated_bloc: ^9.1.1
  injectable_generator: ^2.1.6
  # intl: ^0.18.0
  json_annotation: ^4.8.1
  mockito: ^5.4.1
  modular_bloc_bind: ^1.0.1
  path_provider: ^2.0.15
  responsive_builder: ^0.7.0
  scryfall_api: ^1.2.0

dev_dependencies:
  auto_route_generator: ^7.0.0
  build_runner: ^2.4.4
  envied_generator: ^0.3.0+3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  injectable: ^2.1.1
  json_serializable: ^6.7.0
  modular_test: ^2.0.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
