// Mocks generated by Mockito 5.4.2-wip from annotations
// in sideboard/test/modules/card_search/bloc/card_search_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:hydrated_bloc/src/hydrated_storage.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:scryfall_api/scryfall_api.dart' as _i2;
import 'package:sideboard/core/constants/failure.dart' as _i6;
import 'package:sideboard/modules/mtg_submodule/data/data_index.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeScryfallApiClient_0 extends _i1.SmartFake
    implements _i2.ScryfallApiClient {
  _FakeScryfallApiClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Storage].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorage extends _i1.Mock implements _i3.Storage {
  @override
  dynamic read(String? key) => super.noSuchMethod(
        Invocation.method(
          #read,
          [key],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<void> write(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> delete(String? key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ScryfallRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockScryfallRepository extends _i1.Mock
    implements _i5.ScryfallRepository {
  @override
  _i2.ScryfallApiClient get apiClient => (super.noSuchMethod(
        Invocation.getter(#apiClient),
        returnValue: _FakeScryfallApiClient_0(
          this,
          Invocation.getter(#apiClient),
        ),
        returnValueForMissingStub: _FakeScryfallApiClient_0(
          this,
          Invocation.getter(#apiClient),
        ),
      ) as _i2.ScryfallApiClient);
  @override
  _i4.Future<(_i6.Failure?, _i5.MtgCardModel?)> getMtgCardByID(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMtgCardByID,
          [id],
        ),
        returnValue:
            _i4.Future<(_i6.Failure?, _i5.MtgCardModel?)>.value((null, null)),
        returnValueForMissingStub:
            _i4.Future<(_i6.Failure?, _i5.MtgCardModel?)>.value((null, null)),
      ) as _i4.Future<(_i6.Failure?, _i5.MtgCardModel?)>);
  @override
  _i4.Future<(_i6.Failure?, _i5.PaginableList<_i5.MtgCardModel>?)>
      getMtgCardsBySearch(String? searchStr) => (super.noSuchMethod(
            Invocation.method(
              #getMtgCardsBySearch,
              [searchStr],
            ),
            returnValue: _i4.Future<
                (
                  _i6.Failure?,
                  _i5.PaginableList<_i5.MtgCardModel>?
                )>.value((null, null)),
            returnValueForMissingStub: _i4.Future<
                (
                  _i6.Failure?,
                  _i5.PaginableList<_i5.MtgCardModel>?
                )>.value((null, null)),
          ) as _i4
              .Future<(_i6.Failure?, _i5.PaginableList<_i5.MtgCardModel>?)>);
}
